### ISSUE TITLE
PhpStorm 6.0 Exception error Ini4Idea 1.0.6

### ISSUE THREAD

**Issue by christopher-hopper** [av239/ini4idea#5]
The details of the error are in the following GIST
https://gist.github.com/chopp3r/5368555#file-gistfile1-txt 

Exception error message:

Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=86,keyText=V,keyChar='',modifiers=Ctrl,extModifiers=Ctrl,keyLocation=KEY_LOCATION_STANDARD,rawCode=86,primaryLevelUnicode=118,scancode=47,extendedKeyCode=0x56] on frame0

**Comment by FatherShawn** [comment]
Similar error on my phpStorm install:
Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=86,keyText=V,keyChar='v',modifiers=⌘,extModifiers=⌘,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame4

phpStorm version 6.0.2
